Re: [PATCH] Stop DTrace config option looping in non-interactive mode Message-Id: <4C6BD298-5CD3-49EA-8FED-4A6DA24BFA7B@hexten.net> Date: Sat, 12 Jan 2008 20:27:46 +0000
p4raw-id: //depot/perl@32967

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -8950,7 +8950,7 @@ DTrace is a diagnosis and performance analysis tool from Sun.
 If this doesn't make any sense to you, just accept the default '$dflt'.
 EOM
 
-while test 1 ; do
+while $test 1 ; do
 	case "$usedtrace" in
 	$define|true|[yY]*) 
 		dflt='y' 
@@ -8983,7 +8983,7 @@ while test 1 ; do
 	set dtrace
 	eval $setvar
 	
-	if test -f $dtrace
+	if $test -f $dtrace
 	then
 		if $dtrace -h -s ../perldtrace.d \
 			-o perldtrace.tmp >/dev/null 2>&1 \
@@ -9005,8 +9005,21 @@ EOM
 		break;
 	fi
 
-	echo "$dtrace was not found."
-	echo " "
+	case "$fastread" in
+	yes)
+		cat >&2 <<EOM
+
+*** $me:  Fatal Error:  $dtrace not found.
+*** Can't continue.
+
+EOM
+		exit 1
+		;;
+	*)
+		echo "*** $dtrace was not found."
+		echo " "
+		;;
+	esac
 done
 
 : define an is-a-typedef? function
