Add dtrace support Message-Id: <F4AC553F-7C7F-49C3-98C2-E04681E1004F@hexten.net>
with fixups as discussed on list, plus adding usedtrace to Glossary,
plus propagating all the new config variables everywhere.
(Was there an automatic way to do that? I did it with emacs macros)

p4raw-id: //depot/perl@32953

sh doesn't know about !
Message-Id: <7EC45604-54BE-4738-90B2-7AC5C6D17026@hexten.net>
Date: Fri, 11 Jan 2008 19:34:25 +0000

p4raw-id: //depot/perl@32963

Re: [PATCH] Stop DTrace config option looping in non-interactive mode
Message-Id: <4C6BD298-5CD3-49EA-8FED-4A6DA24BFA7B@hexten.net>
Date: Sat, 12 Jan 2008 20:27:46 +0000

p4raw-id: //depot/perl@32967

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -225,6 +225,7 @@ cpio=''
 cpp=''
 csh=''
 date=''
+dtrace=''
 echo=''
 egrep=''
 emacs=''
@@ -1159,6 +1160,7 @@ use5005threads=''
 useithreads=''
 usereentrant=''
 usethreads=''
+usedtrace=''
 incpath=''
 mips_type=''
 usrinc=''
@@ -8767,6 +8769,87 @@ esac
 set usefaststdio
 eval $setvar
 
+: DTrace support
+dflt_dtrace='/usr/sbin/dtrace'
+cat <<EOM
+
+Perl can be built to support DTrace on platforms that support it.
+DTrace is a diagnosis and performance analysis tool from Sun.
+
+If this doesn't make any sense to you, just accept the default '$dflt'.
+EOM
+
+while $test 1 ; do
+	case "$usedtrace" in
+	$define|true|[yY]*) 
+		dflt='y' 
+		;;
+	?*)
+		dflt='y' 
+		dflt_dtrace=$usedtrace
+		;;
+	*) 
+		dflt='n' 
+		;;
+	esac
+
+	rp='Support DTrace if available?'
+	. ./myread
+	case "$ans" in
+	y|Y)	val="$define" ;;
+	*)      val="$undef" ;;
+	esac
+	set usedtrace
+	eval $setvar
+
+	test "X$usedtrace" != "X$define" && break
+
+	echo " "
+	rp='Where is the dtrace executable?'
+	dflt=$dflt_dtrace
+	. ./getfile
+	val="$ans"
+	set dtrace
+	eval $setvar
+	
+	if $test -f $dtrace
+	then
+		if $dtrace -h -s ../perldtrace.d \
+			-o perldtrace.tmp >/dev/null 2>&1 \
+			&& rm -f perldtrace.tmp
+		then
+			echo " "
+			echo "Good: your $dtrace knows about the -h flag."
+		else
+			cat >&2 <<EOM
+
+*** $me:  Fatal Error:  $dtrace doesn't support -h flag
+***
+*** Your installed dtrace doesn't support the -h switch to compile a D
+*** program into a C header. Can't continue.
+
+EOM
+			exit 1
+		fi
+		break;
+	fi
+
+	case "$fastread" in
+	yes)
+		cat >&2 <<EOM
+
+*** $me:  Fatal Error:  $dtrace not found.
+*** Can't continue.
+
+EOM
+		exit 1
+		;;
+	*)
+		echo "*** $dtrace was not found."
+		echo " "
+		;;
+	esac
+done
 
 : define an is-a-typedef? function
 typedef='type=$1; var=$2; def=$3; shift; shift; shift; inclist=$@;
@@ -21463,6 +21546,7 @@ dlsrc='$dlsrc'
 doublesize='$doublesize'
 drand01='$drand01'
 drand48_r_proto='$drand48_r_proto'
+dtrace='$dtrace'
 dynamic_ext='$dynamic_ext'
 eagain='$eagain'
 ebcdic='$ebcdic'
@@ -21916,6 +22000,7 @@ use64bitall='$use64bitall'
 use64bitint='$use64bitint'
 usecrosscompile='$usecrosscompile'
 usedl='$usedl'
+usedtrace='$usedtrace'
 usefaststdio='$usefaststdio'
 useithreads='$useithreads'
 uselargefiles='$uselargefiles'
